apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pods-backend
  template:
    metadata:
      labels:
        app: pods-backend
    spec:
      automountServiceAccountToken: false
      containers:
      - name: pods-backend
        image: pods-backend:1.0.0
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "500m"
            memory: "512Mi"
            ephemeral-storage: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: pods-backend-service
spec:
  selector:
    app: pods-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
